name: CI
on: [push, pull_request]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test -- --watch=false
      - run: pnpm run build
